### ISSUE TITLE
how to visualize the results?

### ISSUE THREAD

**Issue by KnightOfTheMoonlight** [openxrlab/xrsfm#10]
Hi, I have run the `auto_reconstruction.py` file successfully. And I think the outputs are generated correctly. However, I don't know how to visualize the ".bin" file. Did I miss something in the tutorial regarding visualization?
For example, `points3D.bin`.

**Comment by oneLOH** [comment]
At present, the visualization part of the code has not been completed. The output format of XRSfM is the same as COLMAP, so a simple solution is to use the colmap gui to view the reconstruction results.

**Comment by KnightOfTheMoonlight** [comment]
This [colmap](https://colmap.github.io/) package?

**Comment by oneLOH** [comment]
Yes,  the steps are [colmap gui]->[File]->[Import model].
