### ISSUE TITLE
Installation Error because of XRPRimer

### ISSUE THREAD

**Issue by SalenGit** [openxrlab/xrsfm#14]
Im flowing the installation guide to build on my server(ubuntu22.04), however it comes with an error when running "cd xrsfm && cmake -B build && cmake --build build -j4", error reports below: 

(torch) salen@salen-server:~/文档/giga_2023/xrprimer/Pangolin/build$ cd xrsfm && cmake -B build && cmake --build build -j4
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:15 (find_package):
  By not providing "FindXRPrimer.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "XRPrimer",
  but CMake did not find one.

  Could not find a package configuration file provided by "XRPrimer" with any
  of the following names:

    XRPrimerConfig.cmake
    xrprimer-config.cmake

  Add the installation prefix of "XRPrimer" to CMAKE_PREFIX_PATH or set
  "XRPrimer_DIR" to a directory containing one of the above files.  If
  "XRPrimer" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
See also "/home/salen/文档/giga_2023/xrprimer/Pangolin/build/xrsfm/build/CMakeFiles/CMakeOutput.log".

I have already installed XRPRimer and Pangolin before using the commands in the guide:

Install [XRPRimer](https://github.com/openxrlab/xrprimer)

git clone git@github.com:openxrlab/xrprimer.git
cd xrprimer
cmake -S . -Bbuild -DBUILD_EXTERNAL=ON -DCMAKE_BUILD_TYPE=Release
cmake --build build --target install -j4
Install Pangolin

git clone git@github.com:stevenlovegrove/Pangolin.git
cd Pangolin && cmake -B build && cmake --build build -j4
cd build
sudo make install

**Comment by oneLOH** [comment]
Please check the path of xrsfm and xrprimer.
They should be in the same folder.
├──xrprimer
├──xrsfm
If your project folder structure is different, need to change CMakeList.txt of XRSfM.

**Comment by oneLOH** [comment]
(https://github.com/openxrlab/xrsfm/commit/5cd8a173e76125028307d3fd3fd8747853c9e876) 提供了不依赖xrprimer的编译方式，应该能够解决这一问题。
