### ISSUE TITLE
Could not find a package configuration file provided by "XRPrimer"

### ISSUE THREAD

**Issue by hands0meX** [openxrlab/xrsfm#16]
你好，按照installation.md执行下来到了：
    cmake -B build && cmake --build build -j4
会有以下报错：
    CMake Error at CMakeLists.txt:15 (find_package):
  By not providing "FindXRPrimer.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "XRPrimer",
  but CMake did not find one.

  Could not find a package configuration file provided by "XRPrimer" with any
  of the following names:

    XRPrimerConfig.cmake
    xrprimer-config.cmake

  Add the installation prefix of "XRPrimer" to CMAKE_PREFIX_PATH or set
  "XRPrimer_DIR" to a directory containing one of the above files.  If
  "XRPrimer" provides a separate development package or SDK, be sure it has
  been installed.

我的目录结构是这样的：
├── Miniconda3-py37_4.12.0-Linux-x86_64.sh
├── Pangolin
├── xrlocalization
├── xrprimer
├── xrsfm
└── xrslam

并且我使用docker环境运行了一遍，也出现了以上问题，希望可以帮忙看下问题，我并不是很熟悉这里的过程。

**Comment by oneLOH** [comment]
可以确认下xrprimer是否编译成功了。如果是xrprimer未成功编译，可以参考https://github.com/openxrlab/xrslam/blob/main/docs/en/installation.md中的内容（需要切换xrprimer的版本xrslam-opencv3.4.7）。

**Comment by JNH-LD** [comment]
通过CMakeList设置cmake_prefix_path可解决

**Comment by oneLOH** [comment]
(https://github.com/openxrlab/xrsfm/commit/5cd8a173e76125028307d3fd3fd8747853c9e876) 提供了不依赖xrprimer的编译方式，应该能够解决这一问题。
