### ISSUE TITLE
xrsfm编译不通过

### ISSUE THREAD

**Issue by boge158** [openxrlab/xrsfm#18]
cuda版本12.0  Ubuntu版本20.4
编译时报以下错误：
/home/zjlab/data/gkb/XRARdemo/xrsfm/3rdparty/SiftGPU/ProgramCU.cu(96): error: texture is not a template

/home/zjlab/data/gkb/XRARdemo/xrsfm/3rdparty/SiftGPU/ProgramCU.cu(97): error: texture is not a template

/home/zjlab/data/gkb/XRARdemo/xrsfm/3rdparty/SiftGPU/ProgramCU.cu(98): error: texture is not a template

/home/zjlab/data/gkb/XRARdemo/xrsfm/3rdparty/SiftGPU/ProgramCU.cu(99): error: texture is not a template

/home/zjlab/data/gkb/XRARdemo/xrsfm/3rdparty/SiftGPU/ProgramCU.cu(100): error: texture is not a template

/home/zjlab/data/gkb/XRARdemo/xrsfm/3rdparty/SiftGPU/ProgramCU.cu(101): error: texture is not a template

/home/zjlab/data/gkb/XRARdemo/xrsfm/3rdparty/SiftGPU/ProgramCU.cu(129): error: no instance of overloaded function "tex1Dfetch" matches the argument list
            argument types are: (<error-type>, int)

/home/zjlab/data/gkb/XRARdemo/xrsfm/3rdparty/SiftGPU/ProgramCU.cu(193): error: no instance of overloaded function "tex1Dfetch" matches the argument list
            argument types are: (<error-type>, int)

/home/zjlab/data/gkb/XRARdemo/xrsfm/3rdparty/SiftGPU/ProgramCU.cu(234): error: no instance of overloaded function "tex1Dfetch" matches the argument list
            argument types are: (<error-type>, int)

**Comment by oneLOH** [comment]
这个问题是由于老版本siftgpu不支持cuda 12导致，已经在(https://github.com/openxrlab/xrsfm/commit/fe5c41fb5486c8ead7b6f6c044dd6d60c6c5727c) 上修复
