### ISSUE TITLE
请问有运行基于NetVLAD50的匹配的脚本么

### ISSUE THREAD

**Issue by drlssl** [openxrlab/xrsfm#19]
大佬好呀，有个问题想请问下，就是这里的match有三个选项，sequential ,covisibility和retrieval，这里的第三个retrieval match方式是不是用的benchmark里面的NetVLAD呀？我没能在文件里面找到和netvlad相关的代码。

**Comment by oneLOH** [comment]
是的，retrieval match对应NetVLAD50，可以通过tutorial.md里面的指令进行匹配。
```
./bin/run_matching images_path retrieval_path matching_type output_path
```
benchmark.md里提供了检索文件retrival_50.txt的下载链接，retrival_50.txt这个文件是通过netvlad生成的。

**Comment by drlssl** [comment]
因为我看到文档里面有说retrieval.txt是用的xrloc生成的，而covisibility的matching方式也一样需要提供retrieval.txt，所以covisibility的matching也一样用的是NetVLAD生成的retrieval.txt吗？

**Comment by oneLOH** [comment]
是的，covisibility模式也需要检索文件。此外，xrloc是通过调用netvlad生成retrieval.txt。
