### ISSUE TITLE
重建的点可以是彩色吗？

### ISSUE THREAD

**Issue by ericufatass** [openxrlab/xrsfm#27]
您好，我运行了xrsfm，重建速度比colmap快许多，但是发现这里的重建出来的点云都是黑的，不像colmap一样有颜色，请问有办法让重建变成彩色吗？（如果会速度稍微慢一点也可以接受）谢谢！

**Comment by oneLOH** [comment]
目前出于效率考虑，没有计算点云颜色。后续的更新会提供一个独立工具对点云进行’染色‘。

**Comment by oneLOH** [comment]
分支(https://github.com/openxrlab/xrsfm/commit/ed7fedbc912f316872afde40f6b97669d7bf2a24) 已经添加了相关功能，请参考[这里](https://github.com/openxrlab/xrsfm/blob/main/docs/zh/tutorial.md#4-%E7%94%9F%E6%88%90%E5%BD%A9%E8%89%B2%E7%82%B9%E4%BA%91%E5%8F%AF%E9%80%89)进行使用。
