### ISSUE TITLE
你好，按照installation.md执行下来到了： cmake -S . -Bbuild -DBUILD_EXTERNAL=ON -DCMAKE_BUILD_TYPE=Release会有以下报错：

### ISSUE THREAD

**Issue by sancunluomu** [openxrlab/xrsfm#33]
-- Found pybind11: /usr/local/include (found version "2.12.0dev1")
CMake Error at cmake/dependencies.cmake:29 (find_package):
  Could not find a package configuration file provided by "PnpSolver" with
  any of the following names:

    PnpSolverConfig.cmake
    pnpsolver-config.cmake

  Add the installation prefix of "PnpSolver" to CMAKE_PREFIX_PATH or set
  "PnpSolver_DIR" to a directory containing one of the above files.  If
  "PnpSolver" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:90 (include)

-- Configuring incomplete, errors occurred!
请问这个pnpsolver在哪安装啊？

**Comment by oneLOH** [comment]
你好，这个问题应该是xrprimer版本不对导致的，旧版本的文档有一些问题，现在已经更新了。你需要将xrprimer切换到指定分支(git checkout xrslam-opencv3.4.7)再进行编译。

**Comment by oneLOH** [comment]
(https://github.com/openxrlab/xrsfm/pull/42) 已经移除了xrprimer相关的依赖
