### ISSUE TITLE
Error: wrong results on colmap demo datasets person-hall

### ISSUE THREAD

**Issue by cv-lab-x** [openxrlab/xrsfm#36]
thanks for your great work, xrsfm is much faster than colmap, but the results seem to be poor, i use the default params in the readme, how to improve the results? 
the link of the demo datasets:  https://demuc.de/colmap/datasets/     Person-hall

**xrsfm results:**

![image](https://github.com/openxrlab/xrsfm/assets/26067407/8387a659-708d-46a9-a270-4ecf78efcc9c)

**the gt:**
![image](https://github.com/openxrlab/xrsfm/assets/26067407/8686dcf0-4532-442f-a0c4-fe64538bfff8)

Looking forward to your reply, thanks! @oneLOH

**Comment by oneLOH** [comment]
Thank you for reporting this issue. 
After ensuring the camera parameters are set correctly, I have observed a noticeable improvement in the reconstruction process. Nevertheless, there are still some problem that need to be addressed. I anticipate that this endeavor will take approximately one to two weeks to complete.

**xrsfm results** (with given camera parameters):
![WXWorkCapture_17101363838763](https://github.com/openxrlab/xrsfm/assets/26155071/3657ed24-8a9d-4a75-9681-c3a6a339347a)

**Comment by oneLOH** [comment]
This commit (https://github.com/openxrlab/xrsfm/commit/3439677f798e73f3ac5aeb00e730fe9aed8eb194)  has already fixed the issue. 
Note that when reconstructing, you need to specify the camera intrinsic parameters.
`./bin/run_reconstruction /data/person-hall/ /data/person-hall/sparse/cameras.txt /cephfs/person-hall/results/`

xrsfm:
![WXWorkCapture_17103840588800](https://github.com/openxrlab/xrsfm/assets/26155071/855a33b5-77ba-4c28-8f91-a288a2faf9d6)

**Comment by cv-lab-x** [comment]
> The main cause of this issue is the incorrect image rotation when using cv::imread without IMREAD_IGNORE_ORIENTATION. The commit ([3439677](https://github.com/openxrlab/xrsfm/commit/3439677f798e73f3ac5aeb00e730fe9aed8eb194)) has already fixed this issue.
> 
> Please note that when calling the reconstruction command, the camera intrinsic parameters need to be specified. `./bin/run_reconstruction /data/person-hall/ /data/person-hall/sparse/cameras.txt /cephfs/person-hall/results/`
> 
> xrsfm results: ![WXWorkCapture_17103840588800](https://private-user-images.githubusercontent.com/26155071/312680390-855a33b5-77ba-4c28-8f91-a288a2faf9d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MTQyMDYsIm5iZiI6MTcxMDUxMzkwNiwicGF0aCI6Ii8yNjE1NTA3MS8zMTI2ODAzOTAtODU1YTMzYjUtNzdiYS00YzI4LThmOTEtYTI4OGEyZmFmOWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDE0NDUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiMDE0ZGFlNzE5YjYwMTc1ZjAxMjI0MDY4N2EwMjE0NjRjYjgxOTlmNTAyM2ZhZTQ3MWRmNzJkYjBmMTBkNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EkApuWIkqpQIVtvugvfoVeM7ov1uv5qw4sMJPN-HTyU)

great, huge improvement,  I'll try,  thanks for your work./
