### ISSUE TITLE
Redefinition error buidling Docker image

### ISSUE THREAD

**Issue by hiracu** [openxrlab/xrsfm#38]
Hello,

I'm getting the following error when building the docker image, 
<details>
<summary>Error from: 
RUN cd xrsfm && cmake --build build -j4
</summary>
`

[  1%] Building NVCC (Device) object 3rdparty/SiftGPU/CMakeFiles/sift_gpu.dir/sift_gpu_generated_ProgramCU.cu.o
[  3%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/apriltag_quad_thresh.c.o
[  3%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/apriltag.c.o
[  4%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/apriltag_pose.c.o
[  5%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/common/g2d.c.o
[  6%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/common/getopt.c.o
[  8%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/common/homography.c.o
[  9%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/common/image_u8.c.o
[ 10%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/common/image_u8x3.c.o
[ 11%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/common/image_u8x4.c.o
[ 12%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/common/matd.c.o
[ 13%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/common/pam.c.o
[ 15%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/common/pjpeg-idct.c.o
[ 16%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/common/pjpeg.c.o
[ 17%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/common/pnm.c.o
[ 18%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/common/string_util.c.o
[ 19%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/common/svd22.c.o
[ 20%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/common/time_util.c.o
[ 22%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/common/unionfind.c.o
[ 23%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/common/workerpool.c.o
[ 24%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/common/zarray.c.o
[ 25%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/common/zhash.c.o
[ 26%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/common/zmaxheap.c.o
[ 27%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/tag16h5.c.o
[ 29%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/tag25h9.c.o
[ 30%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/tag36h10.c.o
[ 31%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/tag36h11.c.o
[ 32%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/tagCircle21h7.c.o
[ 33%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/tagCircle49h12.c.o
[ 34%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/tagCustom48h12.c.o
[ 36%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/tagStandard41h12.c.o
[ 37%] Building C object 3rdparty/apriltag/CMakeFiles/apriltag.dir/tagStandard52h13.c.o
[ 38%] Linking C shared library ../../../lib/libapriltag.so
[ 38%] Built target apriltag
/usr/include/c++/11/type_traits:79:52: error: redefinition of 'constexpr const _Tp std::integral_constant<_Tp, __v>::value'
79 |   template<typename _Tp, _Tp __v>
|                                                    ^
/usr/include/c++/11/type_traits:67:29: note: 'constexpr const _Tp value' previously declared here
67 |       static constexpr _Tp                  value = __v;
|                             ^~~~~
CMake Error at sift_gpu_generated_ProgramCU.cu.o.Release.cmake:280 (message):
Error generating file
/xrsfm/build/3rdparty/SiftGPU/CMakeFiles/sift_gpu.dir//./sift_gpu_generated_ProgramCU.cu.o

gmake[2]: *** [3rdparty/SiftGPU/CMakeFiles/sift_gpu.dir/build.make:77: 3rdparty/SiftGPU/CMakeFiles/sift_gpu.dir/sift_gpu_generated_ProgramCU.cu.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:347: 3rdparty/SiftGPU/CMakeFiles/sift_gpu.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
`
</details>

Other info,
Windows 11, Docker 25.0.3

I'd appreciate any guidance on fixing this issue.

Thanks

**Comment by VolkaJ** [comment]
`ERROR: failed to solve: nvidia/cuda:10.2-devel-ubuntu18.04: docker.io/nvidia/cuda:10.2-devel-ubuntu18.04: not found `

I get this error when building the image.

**Comment by VolkaJ** [comment]
I get the same error 
![Screen Shot 2024-04-17 at 3 26 50 PM](https://github.com/openxrlab/xrsfm/assets/37435979/fb094491-01a1-46c7-9640-832910a2c22c)

**Comment by VolkaJ** [comment]
![Screen Shot 2024-04-17 at 3 27 41 PM](https://github.com/openxrlab/xrsfm/assets/37435979/10e75547-dd7a-474c-a2e6-bddc14fad066)
I get the same error.

**Comment by VolkaJ** [comment]
FYI, compatibility between NVCC (NVIDIA CUDA Compiler) and the GCC (GNU Compiler Collection) version was the issue.

**Comment by oneLOH** [comment]
The issue is most likely caused by the older version of CUDA not supporting C++17, so you can try fixing it by modifying the Dockerfile. (`FROM nvidia/cuda:10.2-devel-ubuntu18.04 -> FROM nvidia/cuda:12.1.0-devel-ubuntu20.04`).
Another alternative to try is to completely delete the build folder, and then compile using `cmake .. -DCUDA_NVCC_FLAGS="--std c++14"`.

**Comment by oneLOH** [comment]
(https://github.com/openxrlab/xrsfm/pull/42) has updated the Docker file and CMake file. I hope this is helpful.
