### ISSUE TITLE
使用run_test_data.py运行测试数据集是在尺度估计这一步报错

### ISSUE THREAD

**Issue by ShineWellSnake** [openxrlab/xrsfm#44]
您好，我在使用测试数据重建的时候，在尺度估计这一步的时候报错了，请帮忙指导一下，谢谢！
`
Frame id: -1 visible point3d num: 0
Time Total 35.062413s
Time reg 2.842823s
Time tri 0.447248s
Time fil 3.288153s
Time merge 8.290524s
Time check 0.163162s
Time LBA 15.206140s
Time GBA 3.789308s
Reconstruction Done!
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.7) /workspace/xrprimer/_ext/opencv/modules/imgproc/src/color.simd_helpers.hpp:88: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<3, 4>; VDcn = cv::impl::{anonymous}::Set<1>; VDepth = cv::impl::{anonymous}::Set<0, 2, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = (cv::impl::<unnamed>::SizePolicy)2; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1

Aborted
`

**Comment by ShineWellSnake** [comment]
我看到更新到了main分支有新的合并[#42 ](url)，我更新了代码，重新编译之后，运行run_test_data.py有了新的报错，请指导一下，谢谢！
`Frame id: -1 visible point3d num: 0
Time Total 27.834605s
Time reg 2.743165s
Time tri 0.153009s
Time fil 2.069266s
Time merge 7.118706s
Time check 0.127722s
Time LBA 11.625330s
Time GBA 3.171085s
Reconstruction Done!
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/imgproc/src/color.cpp, line 9748
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/imgproc/src/color.cpp:9748: error: (-215) scn == 3 || scn == 4 in function cvtColor

Aborted`

**Comment by oneLOH** [comment]
这个问题是由图像转换时出错导致，(https://github.com/openxrlab/xrsfm/pull/45) 已经修复了这个问题。

**Comment by ShineWellSnake** [comment]
更新代码之后使用测试数据集运行成功了，非常感谢！

**Comment by ShineWellSnake** [comment]
您好，请教一下，我使用自己拍的视频抽帧的方式来进行重建，但是在构建过程中报错了，报错如下，请问这是什么原因呢：

`
Frame id: 4 visible point3d num: 1666
Iter 148 4 output_0005.jpg
Initial cost : 65.3043 [px]
Final cost : 9.10601 [px]
PnP 320/1666
Tri 4 1139/1864 7/1278+77
Outlier num1: 1275 Outlier num2: 0
Merge: 0/0 0/0
E0612 03:28:15.739352  1997 track_processor.cc:540] Frame 4: no measurement
-----------------------------------------------
Frame id: -1 visible point3d num: 0
Time Total 2.313029s
Time reg 1.021812s
Time tri 0.812822s
Time fil 0.055723s
Time merge 0.002167s
Time check 0.000000s
Time LBA 0.000000s
Time GBA 0.000000s
Reconstruction Done!
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted
`

**Comment by oneLOH** [comment]
单纯看log很难确定具体是什么原因导致的，如果方便的话，可以提供下视频或图像。

**Comment by ShineWellSnake** [comment]
您好，上传附件超过限制大小了，我传到[百度网盘](https://pan.baidu.com/s/1FoHWzcOyZkvfe7UpAoei6w?pwd=vsuk)了，麻烦您帮我看看
链接：https://pan.baidu.com/s/1FoHWzcOyZkvfe7UpAoei6w?pwd=vsuk 
提取码：vsuk
