### ISSUE TITLE
android demo support 

### ISSUE THREAD

**Issue by toby018** [openxrlab/xrsfm#7]
Do you have an plan to support android demo?

**Comment by oneLOH** [comment]
I'm closing this because the motivation for skipping Android support at this moment is explained in https://github.com/openxrlab/xrslam/issues/5.

**Comment by toby018** [comment]
目前想针对一个特定ANDROID做移植，标定可以另外做，有什么思路吗？



---Original---
From: "Zhichao ***@***.***&gt;
Date: Tue, Nov 1, 2022 11:35 AM
To: ***@***.***&gt;;
Cc: "toby ***@***.******@***.***&gt;;
Subject: Re: [openxrlab/xrsfm] android demo support  (Issue #7)




 
I'm closing this because the motivation for skipping Android support at this moment is explained in openxrlab/xrslam#5.

**Comment by oneLOH** [comment]
需求如果是在安卓上在线跑SfM的话，可能更方便的方案是移植xrslam，如果一定要移植xrsfm的话最主要的工作量在于需要更换特征。
