### ISSUE TITLE
how to build the library as in installation.md

### ISSUE THREAD

**Issue by KnightOfTheMoonlight** [openxrlab/xrsfm#9]
Thanks for sharing this work. I am trying to implement this work on my pc.
However, I am confused about the installation part.
On page [installation](https://github.com/openxrlab/xrsfm/blob/main/docs/en/installation.md), you suggested different dependencies and third-party libraries, and one dockerfile.
Should I install the third-party libraries in the docker container?
Or should I just run everything in my pc directly instead of the docker container?

**Comment by oneLOH** [comment]
I recommend compiling code on the local environment (See [Build from Source] in installation. md)
Dockerfile is provided for users who are not convenient to compile in the local environment.

**Comment by KnightOfTheMoonlight** [comment]
> I recommend compiling code on the local environment (See [Build from Source] in installation. md) Dockerfile is provided for users who are not convenient to compile in the local environment.

Thanks for your clarification! I did follow the build from the source and made it work for me.
